# This workflow will build a C# project with .NET, and cache/restore any dependencies to improve the workflow execution time

name: Math Utility Project (CI applied)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Build with .NET
      run: dotnet build --configuration Release

    - name: Publish artifact
      run: dotnet publish --configuration Release --output ./publish

    - name: Create artifact
      uses: actions/upload-artifact@v2
      with:
        name: MathUtility
        path: ./publish
